
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.ImageIcon;
import javax.swing.JColorChooser;

import java.awt.*;
        import java.io.BufferedReader;
        import java.io.File;
        import java.io.FileNotFoundException;
        import java.io.FileReader;
        import java.io.FileWriter;
        import java.io.IOException;
        import java.util.Scanner;
        import java.util.logging.Level;
        import java.util.logging.Logger;
        import javax.swing.JFileChooser;
        import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author HÜSEYİN AFŞİN
 */
public class Editor extends javax.swing.JFrame {
    int clickeddosya=1,clickeduzenle=1,clickedara=1,clickedsecenekler=1,clickedyardim=1;
    /**
     * Creates new form NewJFrame
     */
    public Editor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dosyabutton = new javax.swing.JButton();
        seceneklerbutton = new javax.swing.JButton();
        yardımbutton = new javax.swing.JButton();
        duzenlebutton = new javax.swing.JButton();
        arabutton = new javax.swing.JButton();
        dosyapanel = new javax.swing.JPanel();
        yenibutton = new javax.swing.JButton();
        yazdir = new javax.swing.JButton();
        acbutton = new javax.swing.JButton();
        cikis = new javax.swing.JButton();
        kaydetbutton = new javax.swing.JButton();
        duzenlepanel = new javax.swing.JPanel();
        ileriButton = new javax.swing.JButton();
        kesButton = new javax.swing.JButton();
        tumunusec = new javax.swing.JButton();
        kopyalaButton = new javax.swing.JButton();
        yapistirButton = new javax.swing.JButton();
        silButton = new javax.swing.JButton();
        geriButton = new javax.swing.JButton();
        arapanel = new javax.swing.JPanel();
        oncekiButton = new javax.swing.JButton();
        sonrakiButton = new javax.swing.JButton();
        gitButton = new javax.swing.JButton();
        degistirButon = new javax.swing.JButton();
        bulButton = new javax.swing.JButton();
        seceneklerpanel = new javax.swing.JPanel();
        yazitipi = new javax.swing.JButton();
        background = new javax.swing.JButton();
        foregrondButton = new javax.swing.JButton();
        yaziboyutButton = new javax.swing.JButton();
        yaziboyutButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	Font defaultFont=textarea.getFont();
        	
        	String input=JOptionPane.showInputDialog("Font boyutu giriniz");
        	int in=Integer.parseInt(input);
       
        	Font myFont = new Font(defaultFont.getFontName(), Font.BOLD,in);
        	textarea.setFont(myFont);

        	}
        });
        yardimpanel = new javax.swing.JPanel();
        hakkimizdaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setForeground(java.awt.Color.darkGray);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.darkGray);

        dosyabutton.setBackground(java.awt.Color.black);
        dosyabutton.setForeground(new java.awt.Color(234, 222, 222));
        dosyabutton.setText("Dosya");
        dosyabutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dosyabuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dosyabuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dosyabuttonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dosyabuttonMouseReleased(evt);
            }
        });
        dosyabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyabuttonActionPerformed(evt);
            }
        });

        seceneklerbutton.setBackground(java.awt.Color.black);
        seceneklerbutton.setForeground(new java.awt.Color(234, 222, 222));
        seceneklerbutton.setText("Seçenekler");
        seceneklerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seceneklerbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seceneklerbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seceneklerbuttonMouseExited(evt);
            }
        });

        yardımbutton.setBackground(java.awt.Color.black);
        yardımbutton.setForeground(new java.awt.Color(234, 222, 222));
        yardımbutton.setText("Yardım");
        yardımbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yardımbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yardımbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yardımbuttonMouseExited(evt);
            }
        });

        duzenlebutton.setBackground(java.awt.Color.black);
        duzenlebutton.setForeground(new java.awt.Color(234, 222, 222));
        duzenlebutton.setText("Düzenle");
        duzenlebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duzenlebuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duzenlebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duzenlebuttonMouseExited(evt);
            }
        });
        duzenlebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duzenlebuttonActionPerformed(evt);
            }
        });


        arabutton.setBackground(java.awt.Color.black);
        arabutton.setForeground(new java.awt.Color(234, 222, 222));
        arabutton.setText("Ara");
        arabutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arabuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arabuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arabuttonMouseExited(evt);
            }
        });
        arabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(dosyabutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(duzenlebutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(arabutton)
                                .addGap(12, 12, 12)
                                .addComponent(seceneklerbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yardımbutton)
                                .addContainerGap(1162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dosyabutton)
                                        .addComponent(duzenlebutton)
                                        .addComponent(seceneklerbutton)
                                        .addComponent(yardımbutton)
                                        .addComponent(arabutton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1520, 30);

        dosyapanel.setSize(0,0);
        dosyapanel.setBackground(java.awt.Color.darkGray);
        dosyapanel.setMinimumSize(new java.awt.Dimension(120, 210));
        dosyapanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dosyapanelMouseEntered(evt);
            }
        });

        yenibutton.setBackground(java.awt.Color.black);
        yenibutton.setForeground(new java.awt.Color(234, 222, 222));
        yenibutton.setText("Yeni..");
        yenibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenibuttonActionPerformed(evt);
            }
        });

        yazdir.setBackground(java.awt.Color.black);
        yazdir.setForeground(new java.awt.Color(234, 222, 222));
        yazdir.setText("Yazdır");
        yazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yazdirActionPerformed(evt);
            }
        });

        acbutton.setBackground(java.awt.Color.black);
        acbutton.setForeground(new java.awt.Color(234, 222, 222));
        acbutton.setText("Aç");
        acbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acbuttonActionPerformed(evt);
            }
        });

        cikis.setBackground(java.awt.Color.black);
        cikis.setForeground(new java.awt.Color(234, 222, 222));
        cikis.setText("Çık");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        kaydetbutton.setBackground(java.awt.Color.black);
        kaydetbutton.setForeground(new java.awt.Color(234, 222, 222));
        kaydetbutton.setText("Kaydet");
        kaydetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dosyapanelLayout = new javax.swing.GroupLayout(dosyapanel);
        dosyapanel.setLayout(dosyapanelLayout);
        dosyapanelLayout.setHorizontalGroup(
                dosyapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dosyapanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(dosyapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(yenibutton)
                                        .addComponent(yazdir)
                                        .addComponent(acbutton)
                                        .addComponent(kaydetbutton)
                                        .addComponent(cikis))
                                .addGap(0, 59, Short.MAX_VALUE))
        );
        dosyapanelLayout.setVerticalGroup(
                dosyapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dosyapanelLayout.createSequentialGroup()
                                .addComponent(yenibutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kaydetbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yazdir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cikis)
                                .addContainerGap())
        );

        getContentPane().add(dosyapanel);
        dosyapanel.setBounds(0, 40, 134, 0);

        duzenlepanel.setBackground(java.awt.Color.darkGray);

        ileriButton.setBackground(java.awt.Color.black);
        ileriButton.setForeground(new java.awt.Color(234, 222, 222));
        ileriButton.setText("İleri");
        ileriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ileriButtonActionPerformed(evt);
            }
        });

        kesButton.setBackground(java.awt.Color.black);
        kesButton.setForeground(new java.awt.Color(234, 222, 222));
        kesButton.setText("Kes");
        kesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kesButtonActionPerformed(evt);
            }
        });

        tumunusec.setBackground(java.awt.Color.black);
        tumunusec.setForeground(new java.awt.Color(234, 222, 222));
        tumunusec.setText("Tümünü Seç");
        tumunusec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tumunusecActionPerformed(evt);
            }
        });

        kopyalaButton.setBackground(java.awt.Color.black);
        kopyalaButton.setForeground(new java.awt.Color(234, 222, 222));
        kopyalaButton.setText("Kopyala");
        kopyalaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kopyalaButtonActionPerformed(evt);
            }
        });

        yapistirButton.setBackground(java.awt.Color.black);
        yapistirButton.setForeground(new java.awt.Color(234, 222, 222));
        yapistirButton.setText("Yapıştır");
        yapistirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yapistirButtonActionPerformed(evt);
            }
        });

        silButton.setBackground(java.awt.Color.black);
        silButton.setForeground(new java.awt.Color(234, 222, 222));
        silButton.setText("Sil");
        silButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButtonActionPerformed(evt);
            }
        });

        geriButton.setBackground(java.awt.Color.black);
        geriButton.setForeground(new java.awt.Color(234, 222, 222));
        geriButton.setText("Geri");
        geriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout duzenlepanelLayout = new javax.swing.GroupLayout(duzenlepanel);
        duzenlepanel.setLayout(duzenlepanelLayout);
        duzenlepanelLayout.setHorizontalGroup(
                duzenlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(duzenlepanelLayout.createSequentialGroup()
                                .addGroup(duzenlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kesButton)
                                        .addComponent(ileriButton)
                                        .addComponent(silButton)
                                        .addComponent(geriButton)
                                        .addComponent(yapistirButton)
                                        .addComponent(kopyalaButton)
                                        .addComponent(tumunusec))
                                .addGap(0, 25, Short.MAX_VALUE))
        );
        duzenlepanelLayout.setVerticalGroup(
                duzenlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(duzenlepanelLayout.createSequentialGroup()
                                .addComponent(geriButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ileriButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kopyalaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yapistirButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(silButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tumunusec)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(duzenlepanel);
        duzenlepanel.setBounds(70, 40, 120, 0);

        arapanel.setBackground(java.awt.Color.darkGray);

        oncekiButton.setBackground(java.awt.Color.black);
        oncekiButton.setForeground(new java.awt.Color(234, 222, 222));
        oncekiButton.setText("Önceki");
        oncekiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oncekiButtonActionPerformed(evt);
            }
        });

        sonrakiButton.setBackground(java.awt.Color.black);
        sonrakiButton.setForeground(new java.awt.Color(234, 222, 222));
        sonrakiButton.setText("Sonraki");
        sonrakiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonrakiButtonActionPerformed(evt);
            }
        });

        gitButton.setBackground(java.awt.Color.black);
        gitButton.setForeground(new java.awt.Color(234, 222, 222));
        gitButton.setText("Git..");
        gitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gitButtonActionPerformed(evt);
            }
        });

        degistirButon.setBackground(java.awt.Color.black);
        degistirButon.setForeground(new java.awt.Color(234, 222, 222));
        degistirButon.setText("Değiştir");
        degistirButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degistirButonActionPerformed(evt);
            }
        });

        bulButton.setBackground(java.awt.Color.black);
        bulButton.setForeground(new java.awt.Color(234, 222, 222));
        bulButton.setText("Bul..");
        bulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout arapanelLayout = new javax.swing.GroupLayout(arapanel);
        arapanel.setLayout(arapanelLayout);
        arapanelLayout.setHorizontalGroup(
                arapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(arapanelLayout.createSequentialGroup()
                                .addGroup(arapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bulButton)
                                        .addComponent(oncekiButton)
                                        .addComponent(sonrakiButton)
                                        .addComponent(degistirButon)
                                        .addComponent(gitButton))
                                .addGap(0, 53, Short.MAX_VALUE))
        );
        arapanelLayout.setVerticalGroup(
                arapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(arapanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bulButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oncekiButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sonrakiButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(degistirButon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gitButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(arapanel);
        arapanel.setBounds(150, 30, 120, 0);

        seceneklerpanel.setBackground(java.awt.Color.darkGray);

        yazitipi.setBackground(java.awt.Color.black);
        yazitipi.setForeground(new java.awt.Color(234, 222, 222));
        yazitipi.setText("Yazı  Tipi");
        yazitipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yazitipiActionPerformed(evt);
            }
        });

        background.setBackground(java.awt.Color.black);
        background.setForeground(new java.awt.Color(234, 222, 222));
        background.setText("Arka Plan");
        background.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundButtonActionPerformed(evt);
            }
        });

        foregrondButton.setBackground(java.awt.Color.black);
        foregrondButton.setForeground(new java.awt.Color(234, 222, 222));
        foregrondButton.setText("Yazı rengi");
        foregrondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foregrondButtonActionPerformed(evt);
            }
        });

        yaziboyutButton.setBackground(java.awt.Color.black);
        yaziboyutButton.setForeground(new java.awt.Color(234, 222, 222));
        yaziboyutButton.setText("Yazı Boyutu");

        javax.swing.GroupLayout seceneklerpanelLayout = new javax.swing.GroupLayout(seceneklerpanel);
        seceneklerpanel.setLayout(seceneklerpanelLayout);
        seceneklerpanelLayout.setHorizontalGroup(
                seceneklerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(seceneklerpanelLayout.createSequentialGroup()
                                .addGroup(seceneklerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(yazitipi)
                                        .addComponent(background)
                                        .addComponent(foregrondButton)
                                        .addComponent(yaziboyutButton))
                                .addGap(0, 14, Short.MAX_VALUE))
        );
        seceneklerpanelLayout.setVerticalGroup(
                seceneklerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(seceneklerpanelLayout.createSequentialGroup()
                                .addComponent(yazitipi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(background)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(foregrondButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yaziboyutButton)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(seceneklerpanel);
        seceneklerpanel.setBounds(200, 30, 120, 0);

        yardimpanel.setBackground(java.awt.Color.darkGray);

        hakkimizdaButton.setBackground(java.awt.Color.black);
        hakkimizdaButton.setForeground(new java.awt.Color(234, 222, 222));
        hakkimizdaButton.setText("Hakkımızda");
        hakkimizdaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hakkimizdaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hakkimizdaButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout yardimpanelLayout = new javax.swing.GroupLayout(yardimpanel);
        yardimpanel.setLayout(yardimpanelLayout);
        yardimpanelLayout.setHorizontalGroup(
                yardimpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(yardimpanelLayout.createSequentialGroup()
                                .addComponent(hakkimizdaButton)
                                .addGap(0, 28, Short.MAX_VALUE))
        );
        yardimpanelLayout.setVerticalGroup(
                yardimpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(yardimpanelLayout.createSequentialGroup()
                                .addComponent(hakkimizdaButton)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(yardimpanel);
        yardimpanel.setBounds(300, 40, 120, 0);

        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane1.setViewportView(textarea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 30, 950, 760);
        getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(1507, 50, 10, 800);

        setSize(new java.awt.Dimension(959, 619));
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void duzenlebuttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void dosyapanelMouseEntered(java.awt.event.MouseEvent evt) {
    }

    private void dosyabuttonMouseEntered(java.awt.event.MouseEvent evt) {
        dosyapanel.setSize(120,210);

    }

    private void dosyabuttonMouseClicked(java.awt.event.MouseEvent evt) {
        dosyapanel.setSize(120,210);
        clickeddosya++;
    }

    private void dosyabuttonMouseReleased(java.awt.event.MouseEvent evt) {
    }

    private void dosyabuttonMouseExited(java.awt.event.MouseEvent evt) {
        if (clickeddosya%2==0) {
            dosyapanel.setSize(120,210);
            return;
        }
        dosyapanel.setSize(0,0);

    }

    private void ileriButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void kesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void geriButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tumunusecActionPerformed(java.awt.event.ActionEvent evt) {
        textarea.selectAll();

        // TODO add your handling code here:
    }

    private void kopyalaButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void yapistirButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void silButtonActionPerformed(java.awt.event.ActionEvent evt) {
        
    	textarea.setText("");
    }

    private void duzenlebuttonMouseEntered(java.awt.event.MouseEvent evt) {
        duzenlepanel.setSize(120,250);
    }

    private void duzenlebuttonMouseExited(java.awt.event.MouseEvent evt) {
        if (clickeduzenle%2==0) {
            duzenlepanel.setSize(120,250);
            return;
        }

        duzenlepanel.setSize(0,0);    }

    private void arabuttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bulButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void oncekiButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void sonrakiButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void gitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void degistirButonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void arabuttonMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        arapanel.setSize(120,190);
    }

    private void arabuttonMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (clickedara%2==0) {
            arapanel.setSize(120,190);
            return;
        }
        arapanel.setSize(0,0);
    }

    private void backgroundButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	Color newColor = JColorChooser.showDialog(null, "Arkaplan rengi seçin", Color.RED);
    	textarea.setBackground(newColor);
    }

    private void foregrondButtonActionPerformed(java.awt.event.ActionEvent evt) {
       
    	Color newColor=JColorChooser.showDialog(this,"Yazı rengi seçin",Color.black);
    	textarea.setForeground(newColor);
    }

    private void seceneklerbuttonMouseEntered(java.awt.event.MouseEvent evt) {
        seceneklerpanel.setSize(120,140);
    }

    private void seceneklerbuttonMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (clickedsecenekler%2==0) {
            seceneklerpanel.setSize(120,140);

            return;
        }
        seceneklerpanel.setSize(0,0);

    }

    private void yardımbuttonMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        yardimpanel.setSize(120,30);

    }

    private void yardımbuttonMouseExited(java.awt.event.MouseEvent evt) {

        // TODO add your handling code here:
        if (clickedyardim%2==0) {
            yardimpanel.setSize(120,30);
            return;
        }
        yardimpanel.setSize(0,0);


    }

    private void hakkimizdaButtonMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void hakkimizdaButtonMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void yenibuttonActionPerformed(java.awt.event.ActionEvent evt) {

        Editor editor=new Editor();
        editor.setVisible(true);
        editor.setLocation((Toolkit.getDefaultToolkit().getScreenSize().height)/2+10,(Toolkit.getDefaultToolkit().getScreenSize().width)/2+10);
        editor.setDefaultCloseOperation(HIDE_ON_CLOSE);
        editor.setLocationRelativeTo(null);


    }

    private void dosyabuttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code her
    }

    private void duzenlebuttonMouseClicked(java.awt.event.MouseEvent evt) {
        duzenlepanel.setSize(120,250);
        clickeduzenle++;
    }

    private void arabuttonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        clickedara++;
    }

    private void seceneklerbuttonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        clickedsecenekler++;
    }

    private void yardımbuttonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        clickedyardim++;
    }

    private void kaydetbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFileChooser fc=new JFileChooser();
        int accept =fc.showSaveDialog(this);

        if (accept==JFileChooser.APPROVE_OPTION) {
            String path=fc.getSelectedFile().getPath();
            FileWriter writer;
            try {

                writer=new FileWriter(path,true);
                writer.write(textarea.getText());
                writer.close();
            } catch (IOException ex) {
                Logger.getLogger(Editor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void acbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fc=new JFileChooser();
        int accept=fc.showOpenDialog(this);
        if (accept==JFileChooser.APPROVE_OPTION) {
            File file=fc.getSelectedFile();
            try {
                String metin="";
                Scanner scanner=new Scanner( new BufferedReader(new FileReader(file)));
                while (scanner.hasNextLine()) {
                    metin+=scanner.nextLine()+"\n";

                }
                textarea.setText(metin);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Editor.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void yazdirActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Yazıcı Hizmeti Bulunamadı");
        // TODO add your handling code here:
    }

    private void yazitipiActionPerformed(java.awt.event.ActionEvent evt) {
    
  	  String fonts[] = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();

    	String input=(String)JOptionPane.showInputDialog(this,"Seç","Custumize",JOptionPane.QUESTION_MESSAGE,null,fonts,null);
    	System.out.println(input);

    		    for ( int i = 0; i < fonts.length; i++ )
    		    {
    		    	if(input==fonts[i]) {
    		    		textarea.setFont(new Font(input,textarea.getFont().getStyle(),textarea.getFont().getSize()));
    		    	}
    		    }
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {
        // TODO add your handling code here:
        ImageIcon icon=new ImageIcon("large.ico");
        setIconImage(icon.getImage());
    }

    /*;
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Editor editor=new Editor();
        editor.setCursor(DEFAULT_CURSOR);
        Cursor cursor=new Cursor(Cursor.DEFAULT_CURSOR);
        editor.textarea.setCursor(cursor);
        editor.setTitle("Başlıksız Dosya");


        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    private javax.swing.JButton acbutton;
    private javax.swing.JButton arabutton;
    private javax.swing.JPanel arapanel;
    private javax.swing.JButton bulButton;
    private javax.swing.JButton cikis;
    private javax.swing.JButton degistirButon;
    private javax.swing.JButton dosyabutton;
    private javax.swing.JPanel dosyapanel;
    private javax.swing.JButton duzenlebutton;
    private javax.swing.JPanel duzenlepanel;
    private javax.swing.JButton geriButton;
    private javax.swing.JButton gitButton;
    private javax.swing.JButton hakkimizdaButton;
    private javax.swing.JButton ileriButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaydetbutton;
    private javax.swing.JButton kesButton;
    private javax.swing.JButton kopyalaButton;
    private javax.swing.JButton oncekiButton;
    private javax.swing.JButton yaziboyutButton;
    private javax.swing.JButton foregrondButton;
    private javax.swing.JButton seceneklerbutton;
    private javax.swing.JPanel seceneklerpanel;
    private javax.swing.JButton silButton;
    private javax.swing.JButton sonrakiButton;
    private javax.swing.JButton background;
    private javax.swing.JTextArea textarea;
    private javax.swing.JButton tumunusec;
    private javax.swing.JButton yapistirButton;
    private javax.swing.JPanel yardimpanel;
    private javax.swing.JButton yardımbutton;
    private javax.swing.JButton yazdir;
    private javax.swing.JButton yazitipi;
    private javax.swing.JButton yenibutton;
    // End of variables declaration
}
